//****************************************************************
//  Generated by:  ToTypeScriptD
//  Website:       http://github.com/ToTypeScriptD/ToTypeScriptD
//  Version:       v0.1.5081.42854 - SHA1:66c203d - Debug
//  Date:          12/28/2016 9:24:15 PM
//
//  Assemblies:
//    NativeUI.dll
//
//****************************************************************



declare module NativeUI {

    export interface BarTimerBar {
        Text: string;
        Percentage: number;
        BackgroundColor: System.Drawing.Color;
        ForegroundColor: System.Drawing.Color;
    }

    export interface BigMessageHandler {
    }

    export interface BigMessageThread {
        MessageInstance: NativeUI.BigMessageHandler;
    }

    export interface CheckboxChangeEvent {
    }

    enum HudColor {
        HUD_COLOUR_PURE_WHITE,
        HUD_COLOUR_WHITE,
        HUD_COLOUR_BLACK,
        HUD_COLOUR_GREY,
        HUD_COLOUR_GREYLIGHT,
        HUD_COLOUR_GREYDARK,
        HUD_COLOUR_RED,
        HUD_COLOUR_REDLIGHT,
        HUD_COLOUR_REDDARK,
        HUD_COLOUR_BLUE,
        HUD_COLOUR_BLUELIGHT,
        HUD_COLOUR_BLUEDARK,
        HUD_COLOUR_YELLOW,
        HUD_COLOUR_YELLOWLIGHT,
        HUD_COLOUR_YELLOWDARK,
        HUD_COLOUR_ORANGE,
        HUD_COLOUR_ORANGELIGHT,
        HUD_COLOUR_ORANGEDARK,
        HUD_COLOUR_GREEN,
        HUD_COLOUR_GREENLIGHT,
        HUD_COLOUR_GREENDARK,
        HUD_COLOUR_PURPLE,
        HUD_COLOUR_PURPLELIGHT,
        HUD_COLOUR_PURPLEDARK,
        HUD_COLOUR_PINK,
        HUD_COLOUR_RADAR_HEALTH,
        HUD_COLOUR_RADAR_ARMOUR,
        HUD_COLOUR_RADAR_DAMAGE,
        HUD_COLOUR_NET_PLAYER1,
        HUD_COLOUR_NET_PLAYER2,
        HUD_COLOUR_NET_PLAYER3,
        HUD_COLOUR_NET_PLAYER4,
        HUD_COLOUR_NET_PLAYER5,
        HUD_COLOUR_NET_PLAYER6,
        HUD_COLOUR_NET_PLAYER7,
        HUD_COLOUR_NET_PLAYER8,
        HUD_COLOUR_NET_PLAYER9,
        HUD_COLOUR_NET_PLAYER10,
        HUD_COLOUR_NET_PLAYER11,
        HUD_COLOUR_NET_PLAYER12,
        HUD_COLOUR_NET_PLAYER13,
        HUD_COLOUR_NET_PLAYER14,
        HUD_COLOUR_NET_PLAYER15,
        HUD_COLOUR_NET_PLAYER16,
        HUD_COLOUR_NET_PLAYER17,
        HUD_COLOUR_NET_PLAYER18,
        HUD_COLOUR_NET_PLAYER19,
        HUD_COLOUR_NET_PLAYER20,
        HUD_COLOUR_NET_PLAYER21,
        HUD_COLOUR_NET_PLAYER22,
        HUD_COLOUR_NET_PLAYER23,
        HUD_COLOUR_NET_PLAYER24,
        HUD_COLOUR_NET_PLAYER25,
        HUD_COLOUR_NET_PLAYER26,
        HUD_COLOUR_NET_PLAYER27,
        HUD_COLOUR_NET_PLAYER28,
        HUD_COLOUR_NET_PLAYER29,
        HUD_COLOUR_NET_PLAYER30,
        HUD_COLOUR_NET_PLAYER31,
        HUD_COLOUR_NET_PLAYER32,
        HUD_COLOUR_SIMPLEBLIP_DEFAULT,
        HUD_COLOUR_MENU_BLUE,
        HUD_COLOUR_MENU_GREY_LIGHT,
        HUD_COLOUR_MENU_BLUE_EXTRA_DARK,
        HUD_COLOUR_MENU_YELLOW,
        HUD_COLOUR_MENU_YELLOW_DARK,
        HUD_COLOUR_MENU_GREEN,
        HUD_COLOUR_MENU_GREY,
        HUD_COLOUR_MENU_GREY_DARK,
        HUD_COLOUR_MENU_HIGHLIGHT,
        HUD_COLOUR_MENU_STANDARD,
        HUD_COLOUR_MENU_DIMMED,
        HUD_COLOUR_MENU_EXTRA_DIMMED,
        HUD_COLOUR_BRIEF_TITLE,
        HUD_COLOUR_MID_GREY_MP,
        HUD_COLOUR_NET_PLAYER1_DARK,
        HUD_COLOUR_NET_PLAYER2_DARK,
        HUD_COLOUR_NET_PLAYER3_DARK,
        HUD_COLOUR_NET_PLAYER4_DARK,
        HUD_COLOUR_NET_PLAYER5_DARK,
        HUD_COLOUR_NET_PLAYER6_DARK,
        HUD_COLOUR_NET_PLAYER7_DARK,
        HUD_COLOUR_NET_PLAYER8_DARK,
        HUD_COLOUR_NET_PLAYER9_DARK,
        HUD_COLOUR_NET_PLAYER10_DARK,
        HUD_COLOUR_NET_PLAYER11_DARK,
        HUD_COLOUR_NET_PLAYER12_DARK,
        HUD_COLOUR_NET_PLAYER13_DARK,
        HUD_COLOUR_NET_PLAYER14_DARK,
        HUD_COLOUR_NET_PLAYER15_DARK,
        HUD_COLOUR_NET_PLAYER16_DARK,
        HUD_COLOUR_NET_PLAYER17_DARK,
        HUD_COLOUR_NET_PLAYER18_DARK,
        HUD_COLOUR_NET_PLAYER19_DARK,
        HUD_COLOUR_NET_PLAYER20_DARK,
        HUD_COLOUR_NET_PLAYER21_DARK,
        HUD_COLOUR_NET_PLAYER22_DARK,
        HUD_COLOUR_NET_PLAYER23_DARK,
        HUD_COLOUR_NET_PLAYER24_DARK,
        HUD_COLOUR_NET_PLAYER25_DARK,
        HUD_COLOUR_NET_PLAYER26_DARK,
        HUD_COLOUR_NET_PLAYER27_DARK,
        HUD_COLOUR_NET_PLAYER28_DARK,
        HUD_COLOUR_NET_PLAYER29_DARK,
        HUD_COLOUR_NET_PLAYER30_DARK,
        HUD_COLOUR_NET_PLAYER31_DARK,
        HUD_COLOUR_NET_PLAYER32_DARK,
        HUD_COLOUR_BRONZE,
        HUD_COLOUR_SILVER,
        HUD_COLOUR_GOLD,
        HUD_COLOUR_PLATINUM,
        HUD_COLOUR_GANG1,
        HUD_COLOUR_GANG2,
        HUD_COLOUR_GANG3,
        HUD_COLOUR_GANG4,
        HUD_COLOUR_SAME_CREW,
        HUD_COLOUR_FREEMODE,
        HUD_COLOUR_PAUSE_BG,
        HUD_COLOUR_FRIENDLY,
        HUD_COLOUR_ENEMY,
        HUD_COLOUR_LOCATION,
        HUD_COLOUR_PICKUP,
        HUD_COLOUR_PAUSE_SINGLEPLAYER,
        HUD_COLOUR_FREEMODE_DARK,
        HUD_COLOUR_INACTIVE_MISSION,
        HUD_COLOUR_DAMAGE,
        HUD_COLOUR_PINKLIGHT,
        HUD_COLOUR_PM_MITEM_HIGHLIGHT,
        HUD_COLOUR_SCRIPT_VARIABLE,
        HUD_COLOUR_YOGA,
        HUD_COLOUR_TENNIS,
        HUD_COLOUR_GOLF,
        HUD_COLOUR_SHOOTING_RANGE,
        HUD_COLOUR_FLIGHT_SCHOOL,
        HUD_COLOUR_NORTH_BLUE,
        HUD_COLOUR_SOCIAL_CLUB,
        HUD_COLOUR_PLATFORM_BLUE,
        HUD_COLOUR_PLATFORM_GREEN,
        HUD_COLOUR_PLATFORM_GREY,
        HUD_COLOUR_FACEBOOK_BLUE,
        HUD_COLOUR_INGAME_BG,
        HUD_COLOUR_DARTS,
        HUD_COLOUR_WAYPOINT,
        HUD_COLOUR_MICHAEL,
        HUD_COLOUR_FRANKLIN,
        HUD_COLOUR_TREVOR,
        HUD_COLOUR_GOLF_P1,
        HUD_COLOUR_GOLF_P2,
        HUD_COLOUR_GOLF_P3,
        HUD_COLOUR_GOLF_P4,
        HUD_COLOUR_WAYPOINTLIGHT,
        HUD_COLOUR_WAYPOINTDARK,
        HUD_COLOUR_PANEL_LIGHT,
        HUD_COLOUR_MICHAEL_DARK,
        HUD_COLOUR_FRANKLIN_DARK,
        HUD_COLOUR_TREVOR_DARK,
        HUD_COLOUR_OBJECTIVE_ROUTE,
        HUD_COLOUR_PAUSEMAP_TINT,
        HUD_COLOUR_PAUSE_DESELECT,
        HUD_COLOUR_PM_WEAPONS_PURCHASABLE,
        HUD_COLOUR_PM_WEAPONS_LOCKED,
        HUD_COLOUR_END_SCREEN_BG,
        HUD_COLOUR_CHOP,
        HUD_COLOUR_PAUSEMAP_TINT_HALF,
        HUD_COLOUR_NORTH_BLUE_OFFICIAL,
        HUD_COLOUR_SCRIPT_VARIABLE_2,
        HUD_COLOUR_H,
        HUD_COLOUR_HDARK,
        HUD_COLOUR_T,
        HUD_COLOUR_TDARK,
        HUD_COLOUR_HSHARD,
        HUD_COLOUR_CONTROLLER_MICHAEL,
        HUD_COLOUR_CONTROLLER_FRANKLIN,
        HUD_COLOUR_CONTROLLER_TREVOR,
        HUD_COLOUR_CONTROLLER_CHOP,
        HUD_COLOUR_VIDEO_EDITOR_VIDEO,
        HUD_COLOUR_VIDEO_EDITOR_AUDIO,
        HUD_COLOUR_VIDEO_EDITOR_TEXT,
        HUD_COLOUR_HB_BLUE,
        HUD_COLOUR_HB_YELLOW
    }

    export interface IndexChangedEvent {
    }

    export interface InstructionalButton {
        Text: string;
        ItemBind: NativeUI.UIMenuItem;
    }

    export interface ItemActivatedEvent {
    }

    export interface ItemCheckboxEvent {
    }

    export interface ItemListEvent {
    }

    export interface ItemSelectEvent {
    }

    export interface ListChangedEvent {
    }

    export interface MenuChangeEvent {
    }

    export interface MenuCloseEvent {
    }

    export interface MenuPool {
        MouseEdgeEnabled: boolean;
        ControlDisablingEnabled: boolean;
        ResetCursorOnOpen: boolean;
        FormatDescriptions: boolean;
        AUDIO_LIBRARY: string;
        AUDIO_UPDOWN: string;
        AUDIO_SELECT: string;
        AUDIO_BACK: string;
        AUDIO_ERROR: string;
        WidthOffset: number;
        CounterPretext: string;
        DisableInstructionalButtons: boolean;
    }

    export interface MiscExtensions {
        SharedRandom: any; // System.Random
    }

    export interface Sprite {
        Position: System.Drawing.Point;
        Size: System.Drawing.Size;
        Color: System.Drawing.Color;
        Visible: boolean;
        Heading: number;
        TextureName: string;
        TextureDict: string;
    }

    export interface StringMeasurer {
    }

    export interface TextTimerBar {
        Text: string;
    }

    export interface TimerBarBase {
        Label: string;
    }

    export interface TimerBarPool {
        Offset: System.Drawing.Size;
    }

    export interface UIMenu {
        AUDIO_LIBRARY: string;
        AUDIO_UPDOWN: string;
        AUDIO_LEFTRIGHT: string;
        AUDIO_SELECT: string;
        AUDIO_BACK: string;
        AUDIO_ERROR: string;
        MenuItems: NativeUI.UIMenuItem[];
        MouseEdgeEnabled: boolean;
        ControlDisablingEnabled: boolean;
        ResetCursorOnOpen: boolean;
        FormatDescriptions: boolean;
        MouseControlsEnabled: boolean;
        ScaleWithSafezone: boolean;
        Children: NativeUI.UIMenuItem[];
        WidthOffset: number;
        Visible: boolean;
        CurrentSelection: number;
        IsUsingController: boolean;
        Size: number;
        Title: NativeUI.UIResText;
        Subtitle: NativeUI.UIResText;
        CounterPretext: string;
        ParentMenu: NativeUI.UIMenu;
        ParentItem: NativeUI.UIMenuItem;
    }

    enum UIMenu_MenuControls {
        Up,
        Down,
        Left,
        Right,
        Select,
        Back
    }

    export interface UIMenuCheckboxItem {
        Checked: boolean;
    }

    export interface UIMenuColoredItem {
        MainColor: System.Drawing.Color;
        HighlightColor: System.Drawing.Color;
        TextColor: System.Drawing.Color;
        HighlightedTextColor: System.Drawing.Color;
    }

    export interface UIMenuItem {
        Selected: boolean;
        Hovered: boolean;
        Description: string;
        Enabled: boolean;
        Offset: System.Drawing.Point;
        Text: string;
        RightLabel: string;
        LeftBadge: NativeUI.UIMenuItem_BadgeStyle;
        RightBadge: NativeUI.UIMenuItem_BadgeStyle;
        Parent: NativeUI.UIMenu;
    }

    enum UIMenuItem_BadgeStyle {
        None,
        BronzeMedal,
        GoldMedal,
        SilverMedal,
        Alert,
        Crown,
        Ammo,
        Armour,
        Barber,
        Clothes,
        Franklin,
        Bike,
        Car,
        Gun,
        Heart,
        Makeup,
        Mask,
        Michael,
        Star,
        Tatoo,
        Trevor,
        Lock,
        Tick
    }

    export interface UIMenuListItem {
        Index: number;
    }

    export interface UIResRectangle {
    }

    export interface UIResText {
        TextAlignment: NativeUI.UIResText_Alignment;
        DropShadow: boolean;
        Outline: boolean;
        WordWrap: System.Drawing.Size;
    }

    enum UIResText_Alignment {
        Left,
        Centered,
        Right
    }

}
declare module NativeUI.PauseMenu {

    export interface MissionInformation {
        Name: string;
        Description: string;
        Logo: NativeUI.PauseMenu.MissionLogo;
        ValueList: {Key: string, Value: string}; // System.Tuple<string,string>[]
    }

    export interface MissionLogo {
        FileName: string;
        DictionaryName: string;
    }

    export interface OnItemSelect {
    }

    export interface TabInteractiveListItem {
        Items: NativeUI.UIMenuItem[];
        Index: number;
        IsInList: boolean;
    }

    export interface TabItem {
        DrawBg: boolean;
        Visible: boolean;
        Focused: boolean;
        Title: string;
        Active: boolean;
        JustOpened: boolean;
        CanBeFocused: boolean;
        TopLeft: System.Drawing.Point;
        BottomRight: System.Drawing.Point;
        SafeSize: System.Drawing.Point;
        UseDynamicPositionment: boolean;
        Parent: NativeUI.PauseMenu.TabView;
        FadeInWhenFocused: boolean;
    }

    export interface TabItemSimpleList {
        Dictionary: string[];
    }

    export interface TabMissionSelectItem {
        Heists: NativeUI.PauseMenu.MissionInformation[];
        Index: number;
        _noLogo: NativeUI.Sprite;
    }

    export interface TabSubmenuItem {
        Items: NativeUI.PauseMenu.TabItem[];
        Index: number;
        IsInList: boolean;
        Focused: boolean;
    }

    export interface TabTextItem {
        TextTitle: string;
        Text: string;
        WordWrap: number;
    }

    export interface TabView {
        Index: number;
        Title: string;
        Photo: NativeUI.Sprite;
        Name: string;
        Money: string;
        MoneySubtitle: string;
        Tabs: NativeUI.PauseMenu.TabItem[];
        FocusLevel: number;
        TemporarilyHidden: boolean;
        CanLeave: boolean;
        HideTabs: boolean;
        Visible: boolean;
    }

}

